In [1]:
import torch
import torch.nn as nn

In [17]:
example_input = torch.tensor([
    [[ 0.2, -0.1,  0.4],
     [ 0.5,  0.3, -0.2],
     [-0.3,  0.8,  0.6],
     [ 0.1,  0.0, -0.5]],

    [[-0.6,  0.7,  0.2],
     [ 0.3, -0.2,  0.4],
     [ 0.5, -0.7,  0.1],
     [-0.1,  0.4,  0.3]]
])
example_input

tensor([[[ 0.2000, -0.1000,  0.4000],
         [ 0.5000,  0.3000, -0.2000],
         [-0.3000,  0.8000,  0.6000],
         [ 0.1000,  0.0000, -0.5000]],

        [[-0.6000,  0.7000,  0.2000],
         [ 0.3000, -0.2000,  0.4000],
         [ 0.5000, -0.7000,  0.1000],
         [-0.1000,  0.4000,  0.3000]]])

In [15]:
alpha =nn.Parameter(torch.ones(1))
bias = nn.Parameter(torch.zeros(1))
epsilon = 1e-9

In [11]:
alpha

Parameter containing:
tensor([1.], requires_grad=True)

In [14]:
mean = example_input.mean()
std = example_input.std()

In [16]:
alpha * (example_input - mean) / (std + epsilon) + bias 

tensor([[[ 0.1759, -0.5691,  0.6726],
         [ 0.9209,  0.4242, -0.8174],
         [-1.0658,  1.6659,  1.1692],
         [-0.0724, -0.3208, -1.5624]],

        [[-1.8108,  1.4176,  0.1759],
         [ 0.4242, -0.8174,  0.6726],
         [ 0.9209, -2.0591, -0.0724],
         [-0.5691,  0.6726,  0.4242]]], grad_fn=<AddBackward0>)